### ISSUE TITLE
Support for copy option?

### ISSUE THREAD

**Issue by akashsethiya** [dpostolachi/elxvips#18]
Does this have support for copy functionality?
I want to use it to convert pdf to jpeg
I couldn’t find anything in the documentation

**Comment by dpostolachi** [comment]
Sorry, it's been almost a year since this issue was created.

For generating images from PDFs, the following functions have been added in the version 0.1.3:

* Elxvips.from_pdf( path, opts )

```elixir
      iex> import Elxvips
      iex>
      iex> from_pdf( "/path/input.pdf", page: 0, n: 1 )
      iex> jpg()
      iex> to_file( "output.jpg" )
```

* Elxvips.from_pdf_bytes( bytes, opts )

```elixir
      iex> import Elxvips
      iex>
      iex> file = File.open!( "/path/input.png" )
      iex> bytes = IO.binread( file, :all )
      iex> from_pdf_bytes( bytes, page: 0, n: 1 )
      iex> jpg()
      iex> to_file( "output.jpg" )
```

This should cover the need to extract image from a pdf file.
